### ISSUE TITLE
Matomo Metrics Tracking

### ISSUE THREAD

**Issue by jmc07712** [tischfieldlab/moseq-reports#92]
- [ ] Setup self-hosted Matomo instance
- [ ] Integrate into applications
- [ ] Finalize useful metrics to track
